import "server-only";

import { serviceClient, unwrap, unwrapNullable } from "../db/service";
import type { Garment, Insert, Json } from "../db/types";

/**
 * The garments row: read and write.
 *
 * It lives here rather than in src/lib/server/db/index.ts for the same reason
 * the renders helpers live in src/lib/server/renders/db.ts: this is the only
 * layer that writes it, and the shape of colors and classification is this
 * layer's decision.
 *
 * Every query filters by owner id. The service role client ignores Row Level
 * Security, so that filter is the only thing keeping one person's wardrobe away
 * from another's.
 */

/** Newest first, which is the order the add flow just put them in. */
export async function listGarments(ownerId: string): Promise<Garment[]> {
  const result = await serviceClient()
    .from("garments")
    .select("*")
    .eq("user_id", ownerId)
    .order("created_at", { ascending: false });
  return unwrap("list garments", result);
}

export async function getGarment(
  ownerId: string,
  garmentId: string,
): Promise<Garment | null> {
  const result = await serviceClient()
    .from("garments")
    .select("*")
    .eq("id", garmentId)
    .eq("user_id", ownerId)
    .maybeSingle();
  return unwrapNullable("read garment", result);
}

export async function countGarments(ownerId: string): Promise<number> {
  const result = await serviceClient()
    .from("garments")
    .select("id", { count: "exact", head: true })
    .eq("user_id", ownerId);
  if (result.error !== null) {
    throw new Error(`count garments failed: ${result.error.message}`);
  }
  return result.count ?? 0;
}

/**
 * Writes one garment row.
 *
 * The id is supplied by the caller rather than generated by the database,
 * because storage_path is not null and the path convention is
 * garments/<owner_id>/<garment_id>.<ext>: the row cannot be written before the
 * id exists, so the app makes it.
 */
export async function insertGarment(row: Insert<"garments">): Promise<Garment> {
  const result = await serviceClient()
    .from("garments")
    .insert(row)
    .select("*")
    .single();
  return unwrap("create garment", result);
}

export async function updateGarment(
  ownerId: string,
  garmentId: string,
  patch: {
    readonly type?: string | null;
    readonly colors?: Json;
    readonly pattern?: string | null;
    readonly formality?: "casual" | "smart" | "formal" | null;
    readonly classification?: Json | null;
    readonly user_edited?: boolean;
  },
): Promise<Garment | null> {
  const result = await serviceClient()
    .from("garments")
    .update(patch)
    .eq("id", garmentId)
    .eq("user_id", ownerId)
    .select("*")
    .maybeSingle();
  return unwrapNullable("update garment", result);
}

/**
 * Removes the row. The object is removed by the caller, which owns the order:
 * docs/06-safety-privacy.md says "deleting a garment deletes its object", and
 * the object goes first so a failed row delete never leaves a photo behind with
 * nothing pointing at it.
 */
export async function deleteGarmentRow(
  ownerId: string,
  garmentId: string,
): Promise<void> {
  const result = await serviceClient()
    .from("garments")
    .delete()
    .eq("id", garmentId)
    .eq("user_id", ownerId)
    .select("id")
    .maybeSingle();
  unwrapNullable("delete garment", result);
}
