/**
 * Seeds the demo profile that judge sessions read, and that every screenshot on
 * the Devpost page is taken from.
 *
 * Spec: docs/07-payments-and-judge-mode.md, "Demo profile". The demo owner is a
 * fixed id rather than an auth user, exactly like a judge session, so the same
 * read paths serve it.
 *
 * Run it with one of:
 *
 *     npm run seed:demo -- --from-fixtures
 *     npm run seed:demo -- --from-golden evals/fixtures/golden --image path\to\selfie.jpg
 *     npm run seed:demo -- --from-fixtures --dry-run
 *
 * The npm script carries "--conditions=react-server". Every module this script
 * imports out of src/lib/server opens with import "server-only", whose default
 * export throws outside a React Server Component. The react-server condition
 * resolves that package to its empty module instead, which is the same escape
 * the eval suites take with vi.mock("server-only").
 *
 * WHY TWO MODES
 *
 * The human holds 40 Perfect Corp trial units in total. Judges therefore get no
 * live analysis at all: the whole judge experience serves this seeded demo
 * profile, and the units are spent once, on the founder's own selfie, in the
 * golden run. That leaves two moments where the demo profile has to exist:
 *
 * 1. --from-fixtures, which works today and needs no credits. It seeds the
 *    checked in demo fixture (src/lib/server/profile/demo-fixture*.ts): the
 *    aesthetic profile, the six garment wardrobe, and the two saved looks.
 *    There is no capture, no analysis, no mask, and no render, because none of
 *    those exist yet and a stand in for a face or a try on would be a made up
 *    picture (docs/06-safety-privacy.md, "Grounding and honesty").
 * 2. --from-golden <dir>, which runs after scripts/golden-run.ts has written its
 *    output directory. It seeds everything above and, in addition, the real
 *    capture, the real analyses with their masks, the real renders, and an
 *    aesthetic profile rebuilt from those analyses through the same functions
 *    the live app builds a profile with, so the seeded row and a live row cannot
 *    drift. <dir> is the golden run's --out folder, and the mode reads that
 *    script's own manifest.json rather than a format of its own.
 *
 * Both modes read the fixture data through the very modules the fixture views
 * are built from, never through a second copy of the numbers.
 *
 * CREDITS
 *
 * This script never calls a provider. It writes rows and objects, nothing else.
 *
 * IDEMPOTENCY, and the choice behind it
 *
 * Delete then insert, scoped to the demo owner id, in one documented order. Not
 * upsert: every row and every object under this owner is generated by this
 * script, so the fixture is the whole truth about it, and an upsert would leave
 * behind rows and objects from an older fixture that no longer has their ids.
 * Deleting first means a re run always lands on exactly what the current
 * fixture describes. Rows go in reverse dependency order (analyses before the
 * captures they reference, the profile before the capture its capture_id points
 * at) and come back in forward order.
 *
 * SECRETS
 *
 * .env.local is read by this script and never printed. No key, no token, and no
 * part of one reaches stdout or stderr; the only environment value ever echoed
 * is the origin of the Supabase project URL, which is public by construction
 * (it is the NEXT_PUBLIC_ one).
 */

import { existsSync, readFileSync } from "node:fs";
import { extname, isAbsolute, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { z } from "zod";

import { BUCKETS, capturePath, maskPath, type BucketName } from "@/lib/server/db/storage";
import {
  ANALYSIS_KINDS,
  type Analysis,
  type AnalysisKind,
  type Database,
  type Insert,
  type Json,
} from "@/lib/server/db/types";
import { DEMO_OWNER_ID } from "@/lib/server/judge";
import { toStoredGarments } from "@/lib/server/looks/stored";
import {
  DEMO_FIXTURE_COLOR_VIEW,
  DEMO_FIXTURE_CONCERNS,
  DEMO_FIXTURE_EYE_COLOR_HEX,
  DEMO_FIXTURE_FACE_SHAPE,
  DEMO_FIXTURE_FITZPATRICK,
  DEMO_FIXTURE_HAIR_COLOR_HEX,
  DEMO_FIXTURE_HAIR_VIEW,
  DEMO_FIXTURE_PALETTE,
  DEMO_FIXTURE_READING,
  DEMO_FIXTURE_REPORT_VIEW,
  DEMO_FIXTURE_SKIN_AGE,
  DEMO_FIXTURE_SKIN_TONE_HEX,
  DEMO_FIXTURE_UNDERTONE,
} from "@/lib/server/profile/demo-fixture";
import {
  DEMO_FIXTURE_LOOKS,
  DEMO_FIXTURE_SAVED_OCCASIONS,
} from "@/lib/server/profile/demo-fixture-looks";
import {
  DEMO_FIXTURE_GARMENT_IMAGES,
  DEMO_FIXTURE_WARDROBE,
} from "@/lib/server/profile/demo-fixture-wardrobe";
import { readProfileFacts } from "@/lib/server/profile/facts";
import { buildFallbackNarrative } from "@/lib/server/profile/fallback";
import {
  canonicalHairstyleParams,
  canonicalMakeupParams,
  paramsHash,
} from "@/lib/server/renders/params";
import {
  MAKEUP_CATEGORIES,
  makeupRenderParamsSchema,
} from "@/lib/shared/color-view";
import { hairstyleRenderParamsSchema } from "@/lib/shared/hair-view";
import type { LookItem } from "@/lib/shared/looks-view";
import { derivePalette } from "@/lib/shared/palette";

/*
 * The golden run is the only thing that knows which call produced which
 * analysis and which shades the makeup render wore. Both are imported from it
 * rather than restated, so the two scripts cannot drift. golden-run.ts runs
 * nothing at import: its entry point is guarded the same way this one is.
 */
import { GOLDEN_STEPS, makeupParamsFrom } from "./golden-run";

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/**
 * Every id this script writes, derived from one prefix.
 *
 * The demo owner id is imported from src/lib/server/judge rather than declared
 * again here, so the seeded rows and the judge read path can never disagree
 * about who owns them. The other ids follow the same obviously synthetic shape,
 * and they are fixed rather than random for one reason: a re run has to land on
 * the same rows and the same object paths, or the storage bucket fills with
 * orphans and the looks stop pointing at the garments they were composed from.
 */
const DEMO_ID_PREFIX = "00000000-0000-4000-8000-";

/** Blocks keep the id families apart and readable at a glance. */
const ID_BLOCK = {
  root: 0x0,
  garment: 0x1,
  look: 0x2,
  render: 0x3,
  analysis: 0x4,
} as const;

export function demoUuid(block: number, index: number): string {
  const suffix = (block * 0x100 + index).toString(16).padStart(12, "0");
  return `${DEMO_ID_PREFIX}${suffix}`;
}

/** The one capture the golden run produces. Null in fixtures mode. */
export const DEMO_CAPTURE_ID = demoUuid(ID_BLOCK.root, 2);

/**
 * The reading_model written with the fixture reading.
 *
 * It has to start with "fallback/", because src/lib/server/profile/report-view.ts
 * reads readingSource as "model" for anything that does not, and no model wrote
 * this reading: it is quoted from docs/01-user-flow.md section F item 2. The
 * suffix names where it actually came from, so a stored reading stays traceable.
 */
export const FIXTURE_READING_MODEL = "fallback/demo-fixture";

// ---------------------------------------------------------------------------
// Tables, buckets, content types
// ---------------------------------------------------------------------------

export type SeedTableName =
  | "captures"
  | "analyses"
  | "garments"
  | "looks"
  | "renders"
  | "aesthetic_profiles";

/**
 * Delete order. Children first, so no delete trips a foreign key and no cascade
 * removes a row this script is about to count. analyses references captures;
 * aesthetic_profiles references captures with on delete set null, which would
 * quietly blank capture_id rather than fail, so it still goes before captures.
 */
const DELETE_ORDER: readonly SeedTableName[] = [
  "analyses",
  "renders",
  "looks",
  "garments",
  "aesthetic_profiles",
  "captures",
];

/** Object path conventions, migration 0006 and src/lib/server/db/storage.ts. */
export function garmentObjectPath(
  ownerId: string,
  garmentId: string,
  extension: string,
): string {
  return `${ownerId}/${garmentId}.${extension}`;
}

export function renderObjectPath(
  ownerId: string,
  renderId: string,
  extension: string,
): string {
  return `${ownerId}/${renderId}.${extension}`;
}

const CONTENT_TYPE_BY_EXTENSION: Readonly<Record<string, string>> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".svg": "image/svg+xml",
};

/** The allow list migration 0006 puts on all four buckets. */
const BUCKET_ALLOWED_MIME: readonly string[] = [
  "image/jpeg",
  "image/png",
  "image/webp",
];

export function contentTypeForFile(fileName: string): string {
  const extension = extname(fileName).toLowerCase();
  const contentType = CONTENT_TYPE_BY_EXTENSION[extension];
  if (contentType === undefined) {
    throw new SeedError(
      `read ${fileName}`,
      `Unsupported image extension "${extension}". Use .jpg, .png, or .webp.`,
    );
  }
  return contentType;
}

/** The extension without its dot, for building an object path from a file. */
function extensionOf(fileName: string): string {
  return extname(fileName).toLowerCase().replace(/^\./u, "");
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export class SeedError extends Error {
  readonly operation: string;

  constructor(operation: string, message: string) {
    super(`${operation} failed: ${message}`);
    this.name = "SeedError";
    this.operation = operation;
  }
}

/**
 * The garments bucket rejects the fixture silhouettes today, and this is the
 * remediation printed when it does. The silhouettes are SVG (they are drawn in
 * code, so they can never be mistaken for a photograph) and migration 0006
 * allows image/jpeg, image/png, and image/webp only.
 *
 * Not fixed here on purpose: changing the allow list is a migration, and a
 * migration is a schema change that belongs in its own PR rather than inside a
 * seed script.
 */
export const GARMENT_MIME_REMEDIATION = [
  "The garments bucket refused image/svg+xml.",
  "Migration 0006 allows image/jpeg, image/png, and image/webp on all four buckets, and the fixture garment images are SVG silhouettes drawn in code (src/lib/server/profile/demo-fixture-wardrobe.ts).",
  "Fix it in one of two ways, then run this again: add image/svg+xml to the garments bucket in a new migration, or replace the six silhouettes with PNG copies of the same shapes.",
].join(" ");

// ---------------------------------------------------------------------------
// The writer seam
// ---------------------------------------------------------------------------

export interface SeedObject {
  readonly bucket: BucketName;
  readonly path: string;
  readonly bytes: Uint8Array;
  readonly contentType: string;
}

/**
 * Everything this script does to Supabase, as five operations.
 *
 * The seam exists so the seeding logic can be exercised with a recording double
 * in a unit test: no network, no keys, no project. Every method throws
 * SeedError on failure rather than returning one, because a half seeded demo
 * profile is not a state anything should carry on from.
 */
export interface SeedWriter {
  deleteOwnedRows(table: SeedTableName, ownerId: string): Promise<void>;
  insertRows<T extends SeedTableName>(
    table: T,
    rows: readonly Insert<T>[],
  ): Promise<void>;
  listObjects(bucket: BucketName, prefix: string): Promise<string[]>;
  removeObjects(bucket: BucketName, paths: readonly string[]): Promise<void>;
  putObject(object: SeedObject): Promise<void>;
}

/** The shape of one PostgREST query builder, narrowed to what is used here. */
interface PostgrestLike {
  insert(rows: unknown): PromiseLike<{ error: { message: string } | null }>;
  delete(): {
    eq(column: string, value: string): PromiseLike<{ error: { message: string } | null }>;
  };
}

/** Folders come back from storage.list with a null id, files with a real one. */
interface StorageEntry {
  readonly name: string;
  readonly id: string | null;
}

const MAX_STORAGE_DEPTH = 2;

export function supabaseWriter(
  client: SupabaseClient<Database, "public">,
): SeedWriter {
  /*
   * One cast, here, and a comment saying why. The table name is a union of
   * literals, so client.from(name) is a union of differently typed builders and
   * calling insert on the union does not typecheck. Row shapes are still fully
   * checked, at the call sites, because insertRows is generic over the table
   * name and takes Insert<T> from src/lib/server/db/types.ts.
   */
  const table = (name: SeedTableName): PostgrestLike =>
    client.from(name) as unknown as PostgrestLike;

  async function walk(
    bucket: BucketName,
    prefix: string,
    depth: number,
    found: string[],
  ): Promise<void> {
    if (depth > MAX_STORAGE_DEPTH) {
      return;
    }
    const { data, error } = await client.storage
      .from(bucket)
      .list(prefix, { limit: 1000 });
    if (error !== null) {
      throw new SeedError(`list ${bucket}/${prefix}`, error.message);
    }
    for (const entry of (data ?? []) as unknown as StorageEntry[]) {
      const path = `${prefix}/${entry.name}`;
      if (entry.id === null) {
        await walk(bucket, path, depth + 1, found);
        continue;
      }
      found.push(path);
    }
  }

  return {
    async deleteOwnedRows(name, ownerId) {
      const { error } = await table(name).delete().eq("user_id", ownerId);
      if (error !== null) {
        throw new SeedError(`delete from ${name}`, error.message);
      }
    },

    async insertRows(name, rows) {
      if (rows.length === 0) {
        return;
      }
      const { error } = await table(name).insert(rows);
      if (error !== null) {
        throw new SeedError(`insert into ${name}`, error.message);
      }
    },

    async listObjects(bucket, prefix) {
      const found: string[] = [];
      await walk(bucket, prefix, 0, found);
      return found;
    },

    async removeObjects(bucket, paths) {
      if (paths.length === 0) {
        return;
      }
      const { error } = await client.storage.from(bucket).remove([...paths]);
      if (error !== null) {
        throw new SeedError(`remove from ${bucket}`, error.message);
      }
    },

    async putObject(object) {
      const { error } = await client.storage
        .from(object.bucket)
        .upload(object.path, object.bytes, {
          contentType: object.contentType,
          upsert: true,
        });
      if (error === null) {
        return;
      }
      const mimeRejected =
        !BUCKET_ALLOWED_MIME.includes(object.contentType) &&
        /mime|content type|content_type/iu.test(error.message);
      throw new SeedError(
        `upload to ${object.bucket}`,
        mimeRejected ? `${error.message}. ${GARMENT_MIME_REMEDIATION}` : error.message,
      );
    },
  };
}

// ---------------------------------------------------------------------------
// Rows built from the checked in fixture
// ---------------------------------------------------------------------------

/**
 * Fixture garment id to the uuid its row carries.
 *
 * The fixture ids ("fixture-g01") are readable labels, not uuids, and
 * garments.id is a uuid column. The mapping is by position in the fixture list,
 * so it is stable for as long as the list is, and every look member is remapped
 * through it before it is written.
 */
export function demoGarmentIdByFixtureId(): Map<string, string> {
  const mapping = new Map<string, string>();
  for (const [index, image] of DEMO_FIXTURE_GARMENT_IMAGES.entries()) {
    mapping.set(image.id, demoUuid(ID_BLOCK.garment, index + 1));
  }
  return mapping;
}

export interface GarmentSeed {
  readonly rows: readonly Insert<"garments">[];
  readonly objects: readonly SeedObject[];
}

/**
 * The six garment rows and their images.
 *
 * The attributes come from DEMO_FIXTURE_WARDROBE and the bytes from
 * DEMO_FIXTURE_GARMENT_IMAGES, which is the same function the fixture image
 * route serves, so a seeded wardrobe and a fixture wardrobe show the same six
 * cards with the same six pictures.
 *
 * classification stays null. The column holds "the full model output including
 * confidence" (migration 0003) and no classifier has ever run on these; the
 * card still reads as classified because garmentClassificationStatus in
 * src/lib/shared/wardrobe-view.ts answers from the type, not from this column.
 */
export function buildGarmentSeed(): GarmentSeed {
  const idByFixtureId = demoGarmentIdByFixtureId();
  const svgById = new Map(
    DEMO_FIXTURE_GARMENT_IMAGES.map((image) => [image.id, image.svg] as const),
  );

  const rows: Insert<"garments">[] = [];
  const objects: SeedObject[] = [];

  for (const garment of DEMO_FIXTURE_WARDROBE.garments) {
    const id = idByFixtureId.get(garment.id);
    const svg = svgById.get(garment.id);
    if (id === undefined || svg === undefined) {
      throw new SeedError(
        "build garment rows",
        `The fixture wardrobe holds "${garment.id}", which has no silhouette. Keep DEMO_FIXTURE_WARDROBE and DEMO_FIXTURE_GARMENT_IMAGES in step.`,
      );
    }
    const path = garmentObjectPath(DEMO_OWNER_ID, id, "svg");
    rows.push({
      id,
      user_id: DEMO_OWNER_ID,
      storage_path: path,
      type: garment.type,
      colors: garment.colors.map((color) => ({
        name: color.name,
        hex: color.hex,
      })) as unknown as Json,
      pattern: garment.pattern,
      formality: garment.formality,
      classification: null,
      user_edited: false,
    });
    objects.push({
      bucket: BUCKETS.garments,
      path,
      bytes: new TextEncoder().encode(svg),
      contentType: "image/svg+xml",
    });
  }

  return { rows, objects };
}

/**
 * The two saved looks, docs/07-payments-and-judge-mode.md: "two saved looks for
 * 'Wedding guest' and 'Interview'".
 *
 * Each is the first look of its occasion, which is where a saved look sits in a
 * live read (src/lib/server/looks/compose.ts orders saved looks first), and the
 * members are written through the real toStoredGarments so the column holds
 * exactly what a live save would have put there.
 */
export function buildLookRows(): Insert<"looks">[] {
  const idByFixtureId = demoGarmentIdByFixtureId();
  const rows: Insert<"looks">[] = [];

  for (const [index, occasion] of DEMO_FIXTURE_SAVED_OCCASIONS.entries()) {
    const view = DEMO_FIXTURE_LOOKS[occasion].looks[0];
    if (view === undefined) {
      throw new SeedError(
        "build look rows",
        `The fixture composes no look for "${occasion}", so there is nothing to save for it.`,
      );
    }

    const items: LookItem[] = view.items.map((item) => {
      if (item.source !== "garment") {
        return item;
      }
      const id = idByFixtureId.get(item.garmentId);
      if (id === undefined) {
        throw new SeedError(
          "build look rows",
          `Look "${view.id}" holds garment "${item.garmentId}", which is not in the fixture wardrobe.`,
        );
      }
      return { ...item, garmentId: id };
    });

    rows.push({
      id: demoUuid(ID_BLOCK.look, index + 1),
      user_id: DEMO_OWNER_ID,
      occasion,
      garments: toStoredGarments(items),
      rationale: view.rationale,
      // Nothing has been rendered on the demo face, so the look has no hero
      // try on to point at. A path to an object that does not exist would make
      // the card claim a picture it cannot show.
      render_path: null,
      is_saved: true,
    });
  }

  return rows;
}

/**
 * The aesthetic profile row for --from-fixtures.
 *
 * Every field is read out of the fixture modules rather than typed again, so a
 * change to the fixture changes this row too. capture_id is null: no photo
 * exists, and pointing at a capture row that was never written would break the
 * foreign key and lie about where the numbers came from.
 */
export function buildFixtureProfileRow(): Insert<"aesthetic_profiles"> {
  const zones = DEMO_FIXTURE_REPORT_VIEW.skinTypeZones;
  return {
    user_id: DEMO_OWNER_ID,
    capture_id: null,
    skin_type_zones: { t_zone: zones.tZone, cheeks: zones.cheeks } as Json,
    concerns: DEMO_FIXTURE_CONCERNS as unknown as Json,
    skin_age: DEMO_FIXTURE_SKIN_AGE,
    fitzpatrick: DEMO_FIXTURE_FITZPATRICK,
    skin_tone_hex: DEMO_FIXTURE_SKIN_TONE_HEX,
    undertone: DEMO_FIXTURE_UNDERTONE,
    undertone_source: DEMO_FIXTURE_COLOR_VIEW.undertoneSource,
    eye_color_hex: DEMO_FIXTURE_EYE_COLOR_HEX,
    hair_color_hex: DEMO_FIXTURE_HAIR_COLOR_HEX,
    face_shape: DEMO_FIXTURE_FACE_SHAPE,
    // Hair type detection needs three photos of the same size and is skipped in
    // the one selfie fan out (docs/04-integrations.md), so it is null on every
    // profile this build writes, seeded or live.
    hair_type: null,
    saved_hair_style_id: DEMO_FIXTURE_HAIR_VIEW.savedStyleId,
    saved_hair_color_name: DEMO_FIXTURE_HAIR_VIEW.savedColorName,
    season: DEMO_FIXTURE_PALETTE.season,
    palette: DEMO_FIXTURE_PALETTE as unknown as Json,
    reading: DEMO_FIXTURE_READING,
    reading_model: FIXTURE_READING_MODEL,
    version: 1,
  };
}

// ---------------------------------------------------------------------------
// The golden run manifest
// ---------------------------------------------------------------------------

/**
 * What scripts/golden-run.ts writes into its output directory, read back.
 *
 * This schema is deliberately a reader of that script's real output rather than
 * a contract of its own, because the golden run is the thing that costs money
 * and it therefore gets to decide the file layout. What it writes:
 *
 *     manifest.json          the run record: the image header, the spend, and
 *                            one entry per provider call with its outputs
 *     <fixtureId>.json       the analyses fixture, holding the normalized
 *                            summary per analysis kind
 *     raw/<step>.json        the validated provider response, bytes stripped
 *     masks/<concern>.<ext>  one mask per concern the skin analysis returned
 *     renders/<step>-N.<ext> the render images
 *
 * Unknown keys are dropped rather than rejected, so the golden run can add to
 * its manifest without breaking this reader.
 *
 * THREE THINGS THE GOLDEN RUN DOES NOT WRITE, and how each is resolved. All
 * three are open items worth closing in golden-run.ts rather than here:
 *
 * 1. A copy of the selfie. It hashes the file at --image and never copies it.
 *    So this script takes --image too, and falls back to a capture.<ext> file
 *    sitting in the golden directory.
 * 2. The makeup shade choices it sent. They are recomputed here with
 *    makeupParamsFrom, the same function the run used, over the same recorded
 *    attributes summary. That reproduces the exact request as long as the run
 *    used the default --makeup-categories; a run with a narrower set needs a
 *    renders/makeup-params.json beside the image, which this reader prefers
 *    whenever it exists.
 * 3. The hairstyle id it sent. Same answer: renders/hairstyle-params.json wins,
 *    and without it the golden run's own default is assumed and printed.
 */
export const goldenManifestSchema = z.object({
  recordedOn: z.string().min(1),
  captureId: z.string().min(1),
  /** Name of the analyses fixture file, or null when no skin analysis landed. */
  fixtureFile: z.string().min(1).nullable(),
  image: z.object({
    sha256: z.string().regex(/^[0-9a-f]{64}$/u),
    contentType: z.string().min(1),
    width: z.number().int().positive().nullable().optional(),
    height: z.number().int().positive().nullable().optional(),
    byteLength: z.number().int().positive().optional(),
  }),
  calls: z.array(
    z.object({
      step: z.string().min(1),
      taskId: z.string().min(1).nullable().optional(),
      state: z.string().min(1),
      tableUnits: z.number().int().min(0).nullable().optional(),
      measuredUnits: z.number().int().min(0).nullable().optional(),
      outputs: z.array(z.string().min(1)),
      error: z.string().nullable().optional(),
    }),
  ),
});

export type GoldenManifest = z.infer<typeof goldenManifestSchema>;

/**
 * The half of the analyses fixture this script needs: one normalized summary per
 * analysis kind, exactly as src/lib/server/jobs/analysis.ts wrote it and exactly
 * as src/lib/server/profile/summaries.ts reads it back.
 */
const goldenFixtureSummariesSchema = z.object({
  summaries: z.object({
    skin: z.unknown(),
    fitzpatrick: z.unknown(),
    attributes: z.unknown(),
    face_shape: z.unknown(),
    hair_type: z.unknown(),
  }),
});

export type GoldenSummaries = Partial<Record<AnalysisKind, unknown>>;

/** A recorded reading, when one was captured beside the run. */
const recordedReadingSchema = z.object({
  reading: z.string().min(1),
  readingModel: z.string().min(1),
});

/** The file a recorded reading is looked for in. Optional in every run. */
export const RECORDED_READING_FILE = "reading.json";

/**
 * Where the golden run's files are read from.
 *
 * An interface rather than a directory string, so a unit test can hand the
 * seeder an in memory run and never touch a disk. An absolute path passes
 * through unchanged, which is how the selfie is read from outside the
 * directory.
 */
export interface FileSource {
  readonly label: string;
  exists(path: string): boolean;
  readJson(path: string): unknown;
  readBytes(path: string): Uint8Array;
}

export function diskSource(root: string): FileSource {
  const full = (path: string): string => resolve(root, path);
  const readFile = (path: string): Buffer => {
    if (!existsSync(full(path))) {
      throw new SeedError("read golden file", `${path} is missing.`);
    }
    return readFileSync(full(path));
  };
  return {
    label: root,
    exists: (path) => existsSync(full(path)),
    readJson(path) {
      /*
       * The leading byte order mark is stripped. Windows editors and PowerShell
       * both write one by default, JSON.parse rejects it, and "Unexpected token"
       * is a useless thing to hand an operator holding a file they just saved.
       */
      const text = readFile(path).toString("utf8").replace(/^\uFEFF/u, "");
      try {
        return JSON.parse(text) as unknown;
      } catch (error) {
        throw new SeedError(
          `read ${path}`,
          error instanceof Error ? error.message : "it is not valid JSON.",
        );
      }
    },
    readBytes(path) {
      return new Uint8Array(readFile(path));
    },
  };
}

export function loadGoldenManifest(source: FileSource): GoldenManifest {
  const parsed = goldenManifestSchema.safeParse(source.readJson("manifest.json"));
  if (!parsed.success) {
    const where = parsed.error.issues
      .map((issue) => `${issue.path.join(".")}: ${issue.message}`)
      .join("; ");
    throw new SeedError("read manifest.json", where);
  }
  return parsed.data;
}

export function loadGoldenSummaries(
  source: FileSource,
  manifest: GoldenManifest,
): GoldenSummaries {
  if (manifest.fixtureFile === null) {
    throw new SeedError(
      "read the analyses fixture",
      "manifest.json has fixtureFile null, which means the golden run produced no skin analysis. There is nothing to build a profile from, so nothing is seeded.",
    );
  }
  const parsed = goldenFixtureSummariesSchema.safeParse(
    source.readJson(manifest.fixtureFile),
  );
  if (!parsed.success) {
    throw new SeedError(`read ${manifest.fixtureFile}`, parsed.error.message);
  }
  const summaries = parsed.data.summaries;
  return {
    skin: summaries.skin ?? undefined,
    fitzpatrick: summaries.fitzpatrick ?? undefined,
    attributes: summaries.attributes ?? undefined,
    face_shape: summaries.face_shape ?? undefined,
    hair_type: summaries.hair_type ?? undefined,
  };
}

/** The names a selfie is looked for under, when --image was not given. */
export const CAPTURE_IMAGE_CANDIDATES: readonly string[] = [
  "capture.jpg",
  "capture.jpeg",
  "capture.png",
  "capture.webp",
];

export function findCaptureImage(
  source: FileSource,
  imagePath: string | null,
): string {
  if (imagePath !== null) {
    return imagePath;
  }
  for (const candidate of CAPTURE_IMAGE_CANDIDATES) {
    if (source.exists(candidate)) {
      return candidate;
    }
  }
  throw new SeedError(
    "find the golden selfie",
    `The golden run records the selfie's hash but never copies the file, and none of ${CAPTURE_IMAGE_CANDIDATES.join(", ")} is in ${source.label}. Pass the same path the run was given: --image <path>.`,
  );
}

/** The extension a captures, masks, or renders object is stored under. */
const EXTENSION_BY_CONTENT_TYPE: Readonly<Record<string, string>> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

export function extensionForContentType(contentType: string): string {
  const extension = EXTENSION_BY_CONTENT_TYPE[contentType.toLowerCase()];
  if (extension === undefined) {
    throw new SeedError(
      "read the capture content type",
      `The buckets accept ${BUCKET_ALLOWED_MIME.join(", ")} (migration 0006) and the run recorded "${contentType}".`,
    );
  }
  return extension;
}

// ---------------------------------------------------------------------------
// Rows built from the golden run
// ---------------------------------------------------------------------------

export interface GoldenInput {
  readonly manifest: GoldenManifest;
  /** One normalized summary per analysis kind, out of the analyses fixture. */
  readonly summaries: GoldenSummaries;
  /** Where the selfie is read from. Absolute, or relative to the run folder. */
  readonly captureImagePath: string;
  readonly source: FileSource;
  /** Lines worth putting in the summary about how a value was resolved. */
  readonly notes: string[];
}

/** A succeeded call, by golden run step name. */
function callsByStep(manifest: GoldenManifest): Map<string, GoldenManifest["calls"][number]> {
  const found = new Map<string, GoldenManifest["calls"][number]>();
  for (const call of manifest.calls) {
    if (call.state === "succeeded") {
      found.set(call.step, call);
    }
  }
  return found;
}

/** What one call actually cost, measured first, then the cost table, then zero. */
function unitsOf(call: GoldenManifest["calls"][number] | undefined): number {
  return call?.measuredUnits ?? call?.tableUnits ?? 0;
}

export function buildCaptureSeed(input: GoldenInput): {
  readonly row: Insert<"captures">;
  readonly object: SeedObject;
} {
  const image = input.manifest.image;
  const path = capturePath(
    DEMO_OWNER_ID,
    DEMO_CAPTURE_ID,
    extensionForContentType(image.contentType),
  );
  return {
    row: {
      id: DEMO_CAPTURE_ID,
      user_id: DEMO_OWNER_ID,
      sha256: image.sha256,
      storage_path: path,
      width: image.width ?? null,
      height: image.height ?? null,
      /*
       * The golden run uploads a file that already passed the quality gate, and
       * it records the image header rather than the gate's three numbers. The
       * column is nullable and null is the honest answer; a made up sharpness
       * would be a number nobody measured.
       */
      quality: null,
      /*
       * Never stamped. deleted_at set means the original is gone; the demo
       * profile keeps its original on purpose, which is the keep_originals true
       * behaviour for this owner (see KEEP_ORIGINALS_NOTE).
       */
      deleted_at: null,
    },
    object: {
      bucket: BUCKETS.captures,
      path,
      bytes: input.source.readBytes(input.captureImagePath),
      contentType: image.contentType,
    },
  };
}

export interface AnalysesSeed {
  readonly rows: readonly Insert<"analyses">[];
  readonly objects: readonly SeedObject[];
}

/**
 * The analyses rows and their masks.
 *
 * One row per summary the golden run recorded, in the order db/types.ts lists
 * the kinds. The step a kind came from is looked up through GOLDEN_STEPS, which
 * is golden-run.ts's own table, so the two scripts cannot disagree about which
 * call produced which analysis.
 *
 * The mask object path is rebuilt with the real maskPath helper, and the file
 * stem becomes the concern key, which is the convention
 * src/lib/server/profile/facts.ts reads a mask back by (concernKeyFromMaskPath).
 * A mask named anything else is still uploaded and still stored on the row; it
 * simply will not attach to a concern, which is what would happen to it in a
 * live run too.
 */
export function buildAnalysesSeed(input: GoldenInput): AnalysesSeed {
  const rows: Insert<"analyses">[] = [];
  const objects: SeedObject[] = [];
  const calls = callsByStep(input.manifest);

  const stepForKind = new Map<AnalysisKind, string>();
  for (const [step, definition] of Object.entries(GOLDEN_STEPS)) {
    if (definition.kind === "analysis") {
      stepForKind.set(definition.analysisKind, step);
    }
  }

  for (const kind of ANALYSIS_KINDS) {
    const summary = input.summaries[kind];
    if (summary === undefined || summary === null) {
      continue;
    }
    const call = calls.get(stepForKind.get(kind) ?? "");
    const outputs = call?.outputs ?? [];

    const maskPaths: string[] = [];
    for (const file of outputs.filter((name) => name.startsWith("masks/"))) {
      const path = maskPath(
        DEMO_OWNER_ID,
        DEMO_CAPTURE_ID,
        fileStem(file),
        extensionOf(file),
      );
      maskPaths.push(path);
      objects.push({
        bucket: BUCKETS.masks,
        path,
        bytes: input.source.readBytes(file),
        contentType: contentTypeForFile(file),
      });
    }

    const rawFile = outputs.find((name) => name.startsWith("raw/"));

    rows.push({
      id: demoUuid(ID_BLOCK.analysis, rows.length + 1),
      capture_id: DEMO_CAPTURE_ID,
      user_id: DEMO_OWNER_ID,
      kind,
      status: "succeeded",
      provider_task_id: call?.taskId ?? null,
      raw: rawFile === undefined ? null : (input.source.readJson(rawFile) as Json),
      summary: summary as Json,
      mask_paths: maskPaths as unknown as Json,
      credits_used: unitsOf(call),
      error: null,
    });
  }

  if (rows.length === 0) {
    throw new SeedError(
      "build analyses rows",
      "The golden run recorded no analysis summary, so there is nothing to build a profile from.",
    );
  }

  return { rows, objects };
}

export interface RendersSeed {
  readonly rows: readonly Insert<"renders">[];
  readonly objects: readonly SeedObject[];
}

/** The golden run's own default, scripts/golden-run.ts DEFAULT_HAIRSTYLE_STYLE_ID. */
export const ASSUMED_HAIRSTYLE_STYLE_ID = "textured-crop";

/** Where a params file is looked for, when the run wrote one. */
export function paramsFileFor(step: string): string {
  return `renders/${step}-params.json`;
}

/**
 * The saved renders.
 *
 * params and params_hash go through the same canonical functions the live render
 * layer uses (src/lib/server/renders/params.ts), so re selecting the same shade
 * or the same style on the demo profile finds this row instead of asking for a
 * credit the human does not have. That only works if the parameters here are the
 * ones the run actually sent, which is why a recorded params file always wins
 * and why every assumption is written into the notes rather than left silent.
 *
 * Only the two kinds the golden run buys are handled. Anything else is a failure
 * rather than a row whose hash nobody can reproduce.
 */
export function buildRendersSeed(input: GoldenInput): RendersSeed {
  const rows: Insert<"renders">[] = [];
  const objects: SeedObject[] = [];
  const calls = callsByStep(input.manifest);

  for (const step of ["makeup", "hairstyle"] as const) {
    const call = calls.get(step);
    if (call === undefined) {
      continue;
    }
    const image = call.outputs.find((name) => name.startsWith("renders/"));
    if (image === undefined) {
      throw new SeedError(
        `read the ${step} render`,
        "The call succeeded but wrote no file under renders/, so there is no picture to seed.",
      );
    }

    const id = demoUuid(ID_BLOCK.render, rows.length + 1);
    const path = renderObjectPath(DEMO_OWNER_ID, id, extensionOf(image));
    const paramsFile = paramsFileFor(step);
    const recorded = input.source.exists(paramsFile)
      ? input.source.readJson(paramsFile)
      : null;

    let params: Json;
    let hash: string;

    if (step === "makeup") {
      const parsed = makeupRenderParamsSchema.safeParse(
        recorded ?? recomputedMakeupParams(input),
      );
      if (!parsed.success) {
        throw new SeedError("read the makeup render params", parsed.error.message);
      }
      const stored = canonicalMakeupParams({
        captureId: DEMO_CAPTURE_ID,
        params: parsed.data,
      });
      params = stored as unknown as Json;
      hash = paramsHash("makeup", stored);
      input.notes.push(
        recorded === null
          ? `The makeup shades were recomputed with makeupParamsFrom over the recorded attributes summary and the default categories (${MAKEUP_CATEGORIES.join(", ")}). If the run was given a narrower --makeup-categories, write ${paramsFile} and seed again, or the saved render will not be found by the cache.`
          : `The makeup shades were read from ${paramsFile}.`,
      );
    } else {
      const parsed = hairstyleRenderParamsSchema.safeParse(
        recorded ?? { styleId: ASSUMED_HAIRSTYLE_STYLE_ID },
      );
      if (!parsed.success) {
        throw new SeedError(
          "read the hairstyle render params",
          parsed.error.message,
        );
      }
      const stored = canonicalHairstyleParams({
        captureId: DEMO_CAPTURE_ID,
        params: parsed.data,
      });
      params = stored as unknown as Json;
      hash = paramsHash("hairstyle", stored);
      input.notes.push(
        recorded === null
          ? `No ${paramsFile}, so the hairstyle id was assumed to be the golden run's default "${ASSUMED_HAIRSTYLE_STYLE_ID}". If the run was given --hairstyle-style, write that file and seed again.`
          : `The hairstyle id was read from ${paramsFile}.`,
      );
    }

    rows.push({
      id,
      user_id: DEMO_OWNER_ID,
      kind: step,
      params,
      params_hash: hash,
      storage_path: path,
      provider_task_id: call.taskId ?? null,
      credits_used: unitsOf(call),
      status: "succeeded",
    });
    objects.push({
      bucket: BUCKETS.renders,
      path,
      bytes: input.source.readBytes(image),
      contentType: contentTypeForFile(image),
    });
  }

  return { rows, objects };
}

/**
 * The makeup shades the run sent, recomputed.
 *
 * makeupParamsFrom is imported from scripts/golden-run.ts rather than written
 * again, so there is exactly one place that decides which swatch of each
 * category the demo profile wears. It is deterministic over the recorded
 * attributes summary, so the same summary always produces the same request.
 */
function recomputedMakeupParams(input: GoldenInput): unknown {
  const params = makeupParamsFrom({
    attributesSummary: input.summaries.attributes,
    captureId: DEMO_CAPTURE_ID,
    categories: MAKEUP_CATEGORIES,
  });
  if (params === null) {
    throw new SeedError(
      "rebuild the makeup render params",
      `The run recorded a makeup render but no attributes summary complete enough to say which shades it wore. Write ${paramsFileFor("makeup")} beside the render and seed again.`,
    );
  }
  return { categories: params.categories };
}

/**
 * The aesthetic profile rebuilt from the real analyses.
 *
 * This is the whole point of the golden run: the row a judge reads is built by
 * readProfileFacts, derivePalette, and buildFallbackNarrative, which are the
 * same three the live app builds a profile with
 * (src/lib/server/profile/build.ts). Nothing here restates a number that those
 * functions can derive, so the seeded profile and a live profile cannot drift.
 *
 * The one thing the live path does that this cannot is call Claude for the
 * reading. If a reading.json sits beside the run, it is used and its model id is
 * stored; otherwise the deterministic fallback writes it, and reading_model says
 * "fallback/..." so the report screen reports it as the fallback, truthfully.
 */
export function buildGoldenProfileRow(
  input: GoldenInput,
  analyses: readonly Insert<"analyses">[],
): Insert<"aesthetic_profiles"> {
  const rows: Analysis[] = analyses.map((row) => ({
    // readProfileFacts never reads the analysis id, so an insert row that has
    // not been given one yet still reads correctly here.
    id: row.id ?? "",
    capture_id: row.capture_id,
    user_id: row.user_id,
    kind: row.kind,
    status: "succeeded",
    provider_task_id: row.provider_task_id ?? null,
    raw: row.raw ?? null,
    summary: row.summary ?? null,
    mask_paths: row.mask_paths ?? null,
    credits_used: row.credits_used ?? 0,
    error: null,
    created_at: "",
    updated_at: "",
  }));

  const facts = readProfileFacts({ captureId: DEMO_CAPTURE_ID, analyses: rows });

  const palette =
    facts.skinToneHex === null || facts.undertone === null
      ? null
      : derivePalette({
          skinToneHex: facts.skinToneHex,
          undertone: facts.undertone,
          eyeColorHex: facts.eyeColorHex,
          hairColorHex: facts.hairColorHex,
          fitzpatrick: facts.fitzpatrick,
        });

  const narrative = buildFallbackNarrative(facts);
  let reading = narrative?.reading ?? null;
  let readingModel = narrative?.readingModel ?? null;

  if (input.source.exists(RECORDED_READING_FILE)) {
    const parsed = recordedReadingSchema.safeParse(
      input.source.readJson(RECORDED_READING_FILE),
    );
    if (!parsed.success) {
      throw new SeedError(`read ${RECORDED_READING_FILE}`, parsed.error.message);
    }
    reading = parsed.data.reading;
    readingModel = parsed.data.readingModel;
    input.notes.push(`The reading was read from ${RECORDED_READING_FILE}.`);
  }

  return {
    user_id: DEMO_OWNER_ID,
    capture_id: DEMO_CAPTURE_ID,
    skin_type_zones: {
      t_zone: facts.zones.tZone,
      cheeks: facts.zones.cheeks,
    } as Json,
    concerns: facts.ranked.map((concern) => ({
      key: concern.key,
      score: concern.score,
      rank: concern.rank,
      mask_path: facts.maskPathByKey.get(concern.key) ?? null,
    })) as unknown as Json,
    skin_age: facts.skinAge,
    fitzpatrick: facts.fitzpatrick,
    skin_tone_hex: facts.skinToneHex,
    undertone: facts.undertone,
    undertone_source: facts.undertone === null ? null : "detected",
    eye_color_hex: facts.eyeColorHex,
    hair_color_hex: facts.hairColorHex,
    face_shape: facts.faceShape,
    hair_type: null,
    saved_hair_style_id: null,
    saved_hair_color_name: null,
    season: palette?.season ?? null,
    palette: palette === null ? null : (palette as unknown as Json),
    reading,
    reading_model: readingModel,
    version: 1,
  };
}

function fileStem(path: string): string {
  const file = path.split(/[\\/]/u).pop() ?? path;
  const dot = file.lastIndexOf(".");
  return dot === -1 ? file : file.slice(0, dot);
}

// ---------------------------------------------------------------------------
// The plan
// ---------------------------------------------------------------------------

export type SeedMode = "fixtures" | "golden";

export interface SeedStep {
  /** Stable id so a run can be talked about step by step. */
  readonly id: string;
  readonly title: string;
  /** Tables and buckets the step writes. */
  readonly writes: readonly string[];
}

export const SEED_PLAN: readonly SeedStep[] = [
  {
    id: "owner",
    title: "Check the demo owner id and report what is not written for it",
    writes: [],
  },
  {
    id: "clear",
    title: "Delete every row and object already owned by the demo id",
    writes: [
      "public.analyses",
      "public.renders",
      "public.looks",
      "public.garments",
      "public.aesthetic_profiles",
      "public.captures",
      "storage:captures",
      "storage:masks",
      "storage:renders",
      "storage:garments",
    ],
  },
  {
    id: "capture",
    title: "Upload the golden selfie and insert its captures row",
    writes: ["storage:captures", "public.captures"],
  },
  {
    id: "analyses",
    title: "Upload the masks and insert the analyses rows",
    writes: ["storage:masks", "public.analyses"],
  },
  {
    id: "wardrobe",
    title: "Upload the six garment images and insert their classified rows",
    writes: ["storage:garments", "public.garments"],
  },
  {
    id: "looks",
    title: "Insert the two saved looks",
    writes: ["public.looks"],
  },
  {
    id: "renders",
    title: "Upload the saved makeup and hairstyle renders and insert their rows",
    writes: ["storage:renders", "public.renders"],
  },
  {
    id: "aesthetic-profile",
    title: "Insert the aesthetic profile with its palette and reading",
    writes: ["public.aesthetic_profiles"],
  },
  {
    id: "product-cache",
    title: "Insert the recorded SerpApi responses",
    writes: ["public.product_cache"],
  },
] as const;

export type StepStatus = "written" | "skipped" | "failed" | "not run";

export interface StepReport {
  readonly id: string;
  readonly title: string;
  status: StepStatus;
  rows: number;
  objects: number;
  note: string;
}

export interface SeedReport {
  readonly mode: SeedMode;
  readonly dryRun: boolean;
  readonly steps: readonly StepReport[];
  /** How a value the golden run did not record was resolved. Empty otherwise. */
  readonly assumptions: readonly string[];
  readonly ok: boolean;
  readonly failure: string | null;
}

/**
 * The retention note this script has to print every time it writes a capture.
 *
 * purge_stale_originals() (migration 0007) left joins profiles and treats a
 * missing keep_originals as false, and the demo owner has no profiles row
 * because profiles.user_id references auth.users and the demo owner is not an
 * auth user. So the demo original becomes purgeable 24 hours after it is
 * written, even though the demo profile is meant to keep it.
 *
 * Not worked around here. Creating an auth user for the demo owner would change
 * what identity data exists, and excluding an id inside a purge function is a
 * migration; both are decisions about consent and retention, which CLAUDE.md
 * says to ask the human about. The two safe answers are printed instead.
 */
export const KEEP_ORIGINALS_NOTE = [
  "The demo capture original is kept: keep_originals is true for this owner by intent.",
  "The daily purge does not know that. purge_stale_originals() reads keep_originals from profiles, the demo owner has no profiles row (profiles.user_id references auth.users), and a missing value counts as false, so the original becomes purgeable 24 hours after this run.",
  "Two safe answers, for the human to pick: re run this seed on the day of judging, or exclude the demo owner id inside purge_stale_originals() in a new migration.",
].join(" ");

/**
 * Why no profiles row is written, printed on every run so it is never a
 * surprise. The demo owner is not an auth user, exactly like a judge session.
 */
export const NO_PROFILES_ROW_NOTE =
  "No profiles row is written: profiles.user_id references auth.users and the demo owner is not an auth user, the same way a judge session is not. Consent for the demo face is a written record kept outside the database (evals/fixtures/README.md).";

/**
 * Why product_cache is left empty. The only shopping responses in the
 * repository are hand written to the documented shape, and serving one would
 * put a price, a store, and a link in front of a judge for a product that does
 * not exist (docs/06-safety-privacy.md, "Grounding and honesty").
 */
export const PRODUCT_CACHE_NOTE =
  "Nothing seeded. The repository holds no recorded SerpApi response yet, and RECORDED_GAP_RESPONSES in src/lib/server/profile/demo-fixture-looks.ts is empty on purpose. The demo shows the empty product state, which is true, until real responses are recorded.";

// ---------------------------------------------------------------------------
// The run
// ---------------------------------------------------------------------------

export interface RunSeedOptions {
  readonly writer: SeedWriter;
  readonly mode: SeedMode;
  readonly golden: GoldenInput | null;
  readonly dryRun: boolean;
  readonly log: (line: string) => void;
}

/**
 * Walks the plan in order and reports what landed.
 *
 * Never throws. A failure stops the run, marks the step that failed, leaves
 * every later step as "not run", and comes back with ok false, so the caller
 * can print one summary that says what was written and what was not.
 */
export async function runSeed(options: RunSeedOptions): Promise<SeedReport> {
  const steps: StepReport[] = SEED_PLAN.map((step) => ({
    id: step.id,
    title: step.title,
    status: "not run",
    rows: 0,
    objects: 0,
    note: "",
  }));
  const byId = new Map(steps.map((step) => [step.id, step] as const));

  const log = options.log;
  const golden = options.mode === "golden" ? options.golden : null;

  const step = (id: string): StepReport => {
    const found = byId.get(id);
    if (found === undefined) {
      throw new SeedError("run seed", `Unknown step "${id}".`);
    }
    return found;
  };

  const putAll = async (objects: readonly SeedObject[]): Promise<void> => {
    for (const object of objects) {
      if (!options.dryRun) {
        await options.writer.putObject(object);
      }
      log(`      ${object.bucket}/${object.path} (${object.contentType})`);
    }
  };

  const insert = async <T extends SeedTableName>(
    table: T,
    rows: readonly Insert<T>[],
  ): Promise<void> => {
    if (!options.dryRun) {
      await options.writer.insertRows(table, rows);
    }
    log(`      ${String(rows.length)} row(s) into public.${table}`);
  };

  let failure: string | null = null;

  try {
    // 1. owner ---------------------------------------------------------------
    {
      const current = step("owner");
      log("[1/9] Demo owner");
      if (DEMO_OWNER_ID !== demoUuid(ID_BLOCK.root, 1)) {
        throw new SeedError(
          "check demo owner",
          `DEMO_OWNER_ID in src/lib/server/judge is "${DEMO_OWNER_ID}", which is not the id this script derives its other ids from. Keep the two in step.`,
        );
      }
      log(`      owner id: ${DEMO_OWNER_ID}`);
      log(`      ${NO_PROFILES_ROW_NOTE}`);
      current.status = "skipped";
      current.note = NO_PROFILES_ROW_NOTE;
    }

    // 2. clear ---------------------------------------------------------------
    {
      const current = step("clear");
      log("[2/9] Clearing anything already owned by the demo id");
      let removed = 0;
      for (const bucket of Object.values(BUCKETS)) {
        const existing = options.dryRun
          ? []
          : await options.writer.listObjects(bucket, DEMO_OWNER_ID);
        if (!options.dryRun && existing.length > 0) {
          await options.writer.removeObjects(bucket, existing);
        }
        removed += existing.length;
        log(`      ${bucket}: ${String(existing.length)} object(s) removed`);
      }
      for (const table of DELETE_ORDER) {
        if (!options.dryRun) {
          await options.writer.deleteOwnedRows(table, DEMO_OWNER_ID);
        }
        log(`      public.${table}: rows for the demo owner deleted`);
      }
      current.status = options.dryRun ? "skipped" : "written";
      current.objects = removed;
      current.note = options.dryRun
        ? "Dry run. Nothing was deleted."
        : "Delete then insert, so a re run lands on exactly the current fixture.";
    }

    // 3. capture -------------------------------------------------------------
    let captureWritten = false;
    {
      const current = step("capture");
      log("[3/9] Capture");
      if (golden === null) {
        current.status = "skipped";
        current.note =
          "No photo exists in fixtures mode, so no capture row and no object. The profile row keeps capture_id null.";
        log(`      ${current.note}`);
      } else {
        const seed = buildCaptureSeed(golden);
        await putAll([seed.object]);
        await insert("captures", [seed.row]);
        captureWritten = true;
        current.status = "written";
        current.rows = 1;
        current.objects = 1;
        current.note = KEEP_ORIGINALS_NOTE;
        log(`      ${KEEP_ORIGINALS_NOTE}`);
      }
    }

    // 4. analyses ------------------------------------------------------------
    let analysisRows: readonly Insert<"analyses">[] = [];
    {
      const current = step("analyses");
      log("[4/9] Analyses and masks");
      if (golden === null) {
        current.status = "skipped";
        current.note =
          "Nothing has been analysed yet. A hand written analysis would put invented numbers on a screen that claims to read a real face.";
        log(`      ${current.note}`);
      } else {
        const seed = buildAnalysesSeed(golden);
        analysisRows = seed.rows;
        await putAll(seed.objects);
        await insert("analyses", seed.rows);
        current.status = "written";
        current.rows = seed.rows.length;
        current.objects = seed.objects.length;
        current.note = seed.rows.map((row) => row.kind).join(", ");
      }
    }

    // 5. wardrobe ------------------------------------------------------------
    {
      const current = step("wardrobe");
      log("[5/9] Wardrobe");
      const seed = buildGarmentSeed();
      log(
        "      The six images are SVG silhouettes drawn in code, not photographs. Migration 0006 does not list image/svg+xml on the garments bucket, so an upload here can be refused. The refusal carries the fix.",
      );
      await putAll(seed.objects);
      await insert("garments", seed.rows);
      current.status = "written";
      current.rows = seed.rows.length;
      current.objects = seed.objects.length;
      current.note = "From the checked in fixture in both modes.";
    }

    // 6. looks ---------------------------------------------------------------
    {
      const current = step("looks");
      log("[6/9] Saved looks");
      const rows = buildLookRows();
      await insert("looks", rows);
      current.status = "written";
      current.rows = rows.length;
      current.note = rows
        .map((row) => row.occasion ?? "unknown occasion")
        .join(", ");
    }

    // 7. renders -------------------------------------------------------------
    {
      const current = step("renders");
      log("[7/9] Saved renders");
      if (golden === null) {
        current.status = "skipped";
        current.note =
          "Nothing has been rendered. A stand in image would be a made up try on.";
        log(`      ${current.note}`);
      } else {
        const seed = buildRendersSeed(golden);
        await putAll(seed.objects);
        await insert("renders", seed.rows);
        current.status = "written";
        current.rows = seed.rows.length;
        current.objects = seed.objects.length;
        current.note = seed.rows.map((row) => row.kind).join(", ");
      }
    }

    // 8. aesthetic profile ---------------------------------------------------
    {
      const current = step("aesthetic-profile");
      log("[8/9] Aesthetic profile");
      const row =
        golden === null
          ? buildFixtureProfileRow()
          : buildGoldenProfileRow(golden, analysisRows);
      await insert("aesthetic_profiles", [row]);
      current.status = "written";
      current.rows = 1;
      current.note =
        golden === null
          ? "Built from the checked in fixture. capture_id is null because no photo exists."
          : `Rebuilt from the real analyses through readProfileFacts, derivePalette, and the fallback narrative. capture_id ${captureWritten ? "points at the golden capture" : "is null"}.`;
      log(`      ${current.note}`);
    }

    // 9. product cache -------------------------------------------------------
    {
      const current = step("product-cache");
      log("[9/9] Product cache");
      current.status = "skipped";
      current.note = PRODUCT_CACHE_NOTE;
      log(`      ${PRODUCT_CACHE_NOTE}`);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    failure = message;
    const running = steps.find((entry) => entry.status === "not run");
    if (running !== undefined) {
      running.status = "failed";
      running.note = message;
    }
  }

  return {
    mode: options.mode,
    dryRun: options.dryRun,
    steps,
    assumptions: golden === null ? [] : [...golden.notes],
    ok: failure === null,
    failure,
  };
}

// ---------------------------------------------------------------------------
// The summary
// ---------------------------------------------------------------------------

function padRight(value: string, width: number): string {
  return value.length >= width ? value : value + " ".repeat(width - value.length);
}

function padLeft(value: string, width: number): string {
  return value.length >= width ? value : " ".repeat(width - value.length) + value;
}

/** The final table, as lines. Returned rather than printed so it is testable. */
export function summaryLines(report: SeedReport): string[] {
  const idWidth = Math.max(4, ...report.steps.map((step) => step.id.length));
  const statusWidth = Math.max(
    6,
    ...report.steps.map((step) => step.status.length),
  );

  const lines: string[] = [];
  lines.push("");
  lines.push(
    `Summary (mode: ${report.mode}${report.dryRun ? ", dry run" : ""})`,
  );
  lines.push(
    `${padRight("step", idWidth)}  ${padRight("status", statusWidth)}  ${padLeft("rows", 5)}  ${padLeft("objects", 7)}`,
  );
  lines.push(
    `${"-".repeat(idWidth)}  ${"-".repeat(statusWidth)}  ${"-".repeat(5)}  ${"-".repeat(7)}`,
  );
  for (const step of report.steps) {
    lines.push(
      `${padRight(step.id, idWidth)}  ${padRight(step.status, statusWidth)}  ${padLeft(String(step.rows), 5)}  ${padLeft(String(step.objects), 7)}`,
    );
  }

  const written = report.steps.filter((step) => step.status === "written");
  const notWritten = report.steps.filter((step) => step.status !== "written");
  lines.push("");
  lines.push(
    `Written: ${written.length === 0 ? "nothing" : written.map((step) => step.id).join(", ")}`,
  );
  lines.push(
    `Not written: ${notWritten.length === 0 ? "nothing" : notWritten.map((step) => `${step.id} (${step.status})`).join(", ")}`,
  );

  lines.push("");
  lines.push("Notes");
  for (const step of report.steps) {
    if (step.note.length > 0) {
      lines.push(`  ${step.id}: ${step.note}`);
    }
  }

  if (report.assumptions.length > 0) {
    lines.push("");
    lines.push("Assumptions, because the golden run did not record the value");
    for (const assumption of report.assumptions) {
      lines.push(`  ${assumption}`);
    }
  }

  if (report.failure !== null) {
    lines.push("");
    lines.push(`Failed: ${report.failure}`);
  }

  return lines;
}

/** 0 when everything the mode asked for landed, 1 when anything did not. */
export function exitCodeForReport(report: SeedReport): number {
  return report.ok ? 0 : 1;
}

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------

/**
 * Only the service role can write the demo profile: the rows are owned by an id
 * that no Supabase session ever holds, so row level security denies every client
 * role by design.
 */
const seedEnvSchema = z.object({
  NEXT_PUBLIC_SUPABASE_URL: z.url(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(20),
});

export type SeedEnv = z.infer<typeof seedEnvSchema>;

/**
 * A .env file, as key and value pairs.
 *
 * Pure and exported so it can be unit tested on a literal string. No test ever
 * reads the real .env.local, and no caller ever prints what this returns.
 *
 * An inline "# comment" after an unquoted value is kept rather than stripped: a
 * value may legitimately contain a hash, and silently truncating a key at one
 * would be worse than keeping a comment nobody wrote.
 */
export function parseEnvFile(text: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const rawLine of text.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith("#")) {
      continue;
    }
    const statement = line.startsWith("export ") ? line.slice(7).trim() : line;
    const equals = statement.indexOf("=");
    if (equals <= 0) {
      continue;
    }
    const key = statement.slice(0, equals).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/u.test(key)) {
      continue;
    }
    let value = statement.slice(equals + 1).trim();
    const quoted =
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")));
    if (quoted) {
      value = value.slice(1, -1);
    }
    values.set(key, value);
  }
  return values;
}

/**
 * Loads .env.local into process.env without overwriting anything already set,
 * so an explicit shell value still wins. Returns how many values were applied.
 * Never returns, logs, or throws a value.
 */
export function loadEnvFile(path: string): number {
  if (!existsSync(path)) {
    return 0;
  }
  let applied = 0;
  for (const [key, value] of parseEnvFile(readFileSync(path, "utf8"))) {
    if (process.env[key] === undefined || process.env[key] === "") {
      process.env[key] = value;
      applied += 1;
    }
  }
  return applied;
}

export function readSeedEnv(): SeedEnv {
  const parsed = seedEnvSchema.safeParse(process.env);
  if (!parsed.success) {
    const missing = parsed.error.issues
      .map((issue) => issue.path.join("."))
      .join(", ");
    throw new SeedError(
      "read environment",
      `Missing or invalid: ${missing}. Fill these in .env.local. Values are never printed.`,
    );
  }
  return parsed.data;
}

/** The origin of a URL, so a log line names the project without its path. */
export function originOf(url: string): string {
  try {
    return new URL(url).origin;
  } catch {
    return "unparseable url";
  }
}

// ---------------------------------------------------------------------------
// Command line
// ---------------------------------------------------------------------------

export interface SeedArgs {
  readonly mode: SeedMode;
  readonly goldenDir: string | null;
  /** The same selfie the golden run was given, since the run never copies it. */
  readonly imagePath: string | null;
  readonly dryRun: boolean;
}

export const USAGE = [
  "Usage:",
  "  npm run seed:demo -- --from-fixtures [--dry-run]",
  "  npm run seed:demo -- --from-golden <dir> [--image <path>] [--dry-run]",
  "",
  "  --from-fixtures   Seed the checked in demo fixture. No capture, no analyses, no renders.",
  "  --from-golden     Seed everything, reading the golden run output in <dir>.",
  "  --image           The selfie the golden run was given. Only needed when <dir> holds no capture.<ext>.",
  "  --dry-run         Print every row and object that would be written. Touches nothing, needs no keys.",
].join("\n");

function valueFor(flag: string, next: string | undefined): string {
  if (next === undefined || next.length === 0 || next.startsWith("--")) {
    throw new SeedError("read arguments", `${flag} needs a value.`);
  }
  return next;
}

export function parseArgs(argv: readonly string[]): SeedArgs {
  let mode: SeedMode | null = null;
  let goldenDir: string | null = null;
  let imagePath: string | null = null;
  let dryRun = false;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--from-fixtures") {
      mode = "fixtures";
      continue;
    }
    if (arg === "--from-golden") {
      mode = "golden";
      goldenDir = valueFor(
        "--from-golden needs the directory the golden run wrote. It",
        argv[index + 1],
      );
      index += 1;
      continue;
    }
    if (arg === "--image") {
      imagePath = valueFor("--image", argv[index + 1]);
      index += 1;
      continue;
    }
    if (arg === "--dry-run") {
      dryRun = true;
      continue;
    }
    throw new SeedError("read arguments", `Unknown argument "${String(arg)}".`);
  }

  if (mode === null) {
    throw new SeedError(
      "read arguments",
      "Pick a mode: --from-fixtures or --from-golden <dir>.",
    );
  }
  return { mode, goldenDir, imagePath, dryRun };
}

/**
 * Everything --from-golden needs, read once, before a single row is written.
 *
 * Reading it all up front is deliberate: a missing file is then a failure that
 * wrote nothing, rather than one that stopped halfway through the profile.
 */
export function loadGoldenRun(args: {
  readonly source: FileSource;
  readonly imagePath: string | null;
}): GoldenInput {
  const manifest = loadGoldenManifest(args.source);
  const summaries = loadGoldenSummaries(args.source, manifest);
  const captureImagePath = findCaptureImage(args.source, args.imagePath);
  const notes: string[] = [];
  if (args.imagePath === null) {
    notes.push(
      `The selfie was found at ${captureImagePath} inside the run folder. The golden run records the hash but never copies the file, so check that this is the same image.`,
    );
  }
  return { manifest, summaries, captureImagePath, source: args.source, notes };
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function main(argv: readonly string[]): Promise<number> {
  let args: SeedArgs;
  try {
    args = parseArgs(argv);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    console.error("");
    console.error(USAGE);
    return 1;
  }

  console.log("Seeding the demo profile");
  console.log(`Mode: ${args.mode}${args.dryRun ? " (dry run)" : ""}`);

  let golden: GoldenInput | null = null;
  let writer: SeedWriter;

  try {
    if (args.mode === "golden") {
      const dir = resolveGoldenDir(args.goldenDir);
      golden = loadGoldenRun({
        source: diskSource(dir),
        imagePath:
          args.imagePath === null
            ? null
            : resolve(process.cwd(), args.imagePath),
      });
      const succeeded = golden.manifest.calls.filter(
        (call) => call.state === "succeeded",
      );
      console.log(`Golden run directory: ${dir}`);
      console.log(
        `Recorded on ${golden.manifest.recordedOn}, ${String(succeeded.length)} succeeded call(s): ${succeeded.map((call) => call.step).join(", ")}`,
      );
    }

    if (args.dryRun) {
      writer = noopWriter();
      console.log("Dry run: no environment is read and nothing is written.");
    } else {
      const applied = loadEnvFile(resolve(process.cwd(), ".env.local"));
      console.log(
        `Loaded ${String(applied)} value(s) from .env.local. No value is ever printed.`,
      );
      const env = readSeedEnv();
      console.log(`Project: ${originOf(env.NEXT_PUBLIC_SUPABASE_URL)}`);
      writer = supabaseWriter(
        createClient<Database, "public">(
          env.NEXT_PUBLIC_SUPABASE_URL,
          env.SUPABASE_SERVICE_ROLE_KEY,
          {
            auth: {
              persistSession: false,
              autoRefreshToken: false,
              detectSessionInUrl: false,
            },
          },
        ),
      );
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    console.error("Nothing was written.");
    return 1;
  }

  console.log("");
  const report = await runSeed({
    writer,
    mode: args.mode,
    golden,
    dryRun: args.dryRun,
    log: (line) => {
      console.log(line);
    },
  });

  for (const line of summaryLines(report)) {
    if (report.ok) {
      console.log(line);
    } else {
      console.error(line);
    }
  }

  return exitCodeForReport(report);
}

/** The golden run directory, absolute, so every later message names one path. */
function resolveGoldenDir(goldenDir: string | null): string {
  if (goldenDir === null) {
    throw new SeedError(
      "read arguments",
      "--from-golden needs the directory holding manifest.json.",
    );
  }
  return isAbsolute(goldenDir) ? goldenDir : resolve(process.cwd(), goldenDir);
}

/** The writer a dry run uses. It is never called, and says so if it ever is. */
function noopWriter(): SeedWriter {
  const refuse = (operation: string): never => {
    throw new SeedError(operation, "A dry run must not write.");
  };
  return {
    deleteOwnedRows: () => refuse("delete rows"),
    insertRows: () => refuse("insert rows"),
    listObjects: () => refuse("list objects"),
    removeObjects: () => refuse("remove objects"),
    putObject: () => refuse("upload object"),
  };
}

/*
 * Run only when this file is the process entry point. Importing it from a test
 * must not seed anything, which is what makes the unit tests possible.
 */
const invokedDirectly =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (invokedDirectly) {
  main(process.argv.slice(2))
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : String(error));
      console.error("Nothing further was written.");
      process.exitCode = 1;
    });
}
